site_name: Event driven Earth Observation Application Package with Argo

theme:
    logo: imgs/icon-eoap.png
    name: material

    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - mermaid2:
      version: 10.6.0
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      theme:
        light: kanagawa/fuji
        dark: kanagawa/wave

markdown_extensions:
  - pymdownx.details
  - abbr
  - admonition
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - attr_list
  - pymdownx.snippets:
      base_path: './'
  - pymdownx.highlight:
      line_spans: __span

extra_css:
  - styles/css/app.css
  
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Introduction: 'index.md'
  - Application Packages: 'packages.md'
  - Training a Machine Learning Model: 
    - Container: 'training-container.md'
    - Run Training Module using CWL Runner: 'training-cwl.md'
  - Run an inference on Real World data: 
    - Container: 'inference-container.md'
    - Stage-in: 'stage-in.md'
    - Run Inference Module using CWL Runner: 'inference-cwl.md'
  - Technical Insights and Learnings: 'insights.md'
  

copyright: <a href="https://img.shields.io/badge/License-CC_BY--SA_4.0-lightgrey.svg">License CC BY-SA 4.0</a>, by <a href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons</a>