[project]
name = "tile-sat-classification"
version = "1.0.0"

[build]
engine = "cluster"

[build.local]
runtime="docker"
registry="ghcr.io/eoap"

[build.cluster]
namespace = "tile-based-training"
serviceAccount = "kaniko-sa"
registry = "ghcr.io/eoap"
secret = "kaniko-secret"

[tools.training]
context = "training/make-ml-model"
path = "training/app-package/tile-sat-training.cwl#tile-sat-training"


[tools.inference]
context = "inference/make-inference"
path = "inference/app-package/tile-sat-inference.cwl#tile-sat-inference"