version: '3'

includes:
  remote: https://raw.githubusercontent.com/eoap/task-files/refs/tags/0.1.0/build-test/Taskfile.yaml

tasks:
  build:
  - task: remote:build

  build-debug:
    cmds: 
    - defer: rm -f skaffold-auto.yaml
    - task: remote:prepare-kaniko
    - |
      skaffold build -f skaffold-auto.yaml 

  build-ttl:
  - task: remote:build-ttl

  prepare:
  - task: remote:prepare-kaniko

  