name: build
on:
  push:
    branches:
      - master
      - main
    paths:
      - 'inference/**'
      - .github/**
      - 'training/**'
      - codemeta.json

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install cwltool
      - run: cwltool --validate training/app-package/tile-sat-training.cwl
      - run: cwltool --validate inference/app-package/tile-sat-inference.cwl

  version:
    needs: validate
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.set-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Extract Version
        run: |
          APP_VERSION=$(cat codemeta.json | jq -r .version)
          if [ -z "$APP_VERSION" ]; then
            echo "Error: Version is missing in codemeta.json"
            exit 1
          fi
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "App version: $APP_VERSION"
      - id: set-version
        run: echo "version=${APP_VERSION}" >> $GITHUB_ENV

  container-build:
    needs: version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - step: training
            path: make-ml-model
          - step: inference
            path: make-inference

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Ensure Version is Set
        run: |
          if [ -z "${{ needs.version.outputs.app-version }}" ]; then
            echo "Error: App version is not set!"
            exit 1
          fi
          echo "App version: ${{ needs.version.outputs.app-version }}"

      - name: Build & Push Docker Image
        run: |
          IMAGE_ID="ghcr.io/parham-membari-terradue/machine-learning-process-new/${{ matrix.step }}:${{ needs.version.outputs.app-version }}"
          DOCKERFILE_PATH="${{ matrix.step }}/${{ matrix.path }}/Dockerfile"
          CONTEXT_PATH="${{ matrix.step }}/${{ matrix.path }}"

          echo "Building Docker image from: $DOCKERFILE_PATH"
          docker build "$CONTEXT_PATH" --file "$DOCKERFILE_PATH" --tag "${{ matrix.step }}"

          echo "Tagging image as: $IMAGE_ID"
          docker tag "${{ matrix.step }}" "$IMAGE_ID"

          echo "Pushing image: $IMAGE_ID"
          docker push "$IMAGE_ID"

  create-release:
    needs:
      - container-build
      - version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.set-upload-url.outputs.upload_url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check if Release Already Exists
        id: check_release
        run: |
          git fetch --tags
          if git ls-remote --tags origin | grep -q "refs/tags/${{ needs.version.outputs.app-version }}"; then
            echo "Tag already exists. Creating a new release with a different version."
            NEW_VERSION=$(echo "${{ needs.version.outputs.app-version }}" | awk -F. -v OFS=. '{$NF += 1 ; print}')
            echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
            echo "Creating a new release: $NEW_VERSION"
          else
            echo "Using existing version: ${{ needs.version.outputs.app-version }}"
            echo "NEW_VERSION=${{ needs.version.outputs.app-version }}" >> $GITHUB_ENV
          fi

      - name: Create GitHub Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ env.NEW_VERSION }}
          tag_name: ${{ env.NEW_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Upload URL
        run: echo "upload_url=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV

  publish-artifacts:
    needs:
      - create-release
      - version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: tile-sat-training
            path: training/app-package/tile-sat-training.cwl
          - name: tile-sat-inference
            path: inference/app-package/tile-sat-inference.cwl
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Verify CWL Files Exist
        run: |
          if [ ! -f "${{ matrix.path }}" ]; then
            echo "ERROR: CWL file does not exist: ${{ matrix.path }}"
            exit 1
          fi

      - name: Update CWL files with Docker Image Tags
        run: |
          for step in training inference
          do
            tag="ghcr.io/parham-membari-terradue/machine-learning-process-new/${step}:${{ needs.version.outputs.app-version }}"
            docker pull ${tag}
            shatag=$( docker inspect ${tag} | yq -r '.[0]["RepoDigests"][0]' )
            cwl_path="${{ matrix.path }}"

            echo "✅ Updating CWL file: $cwl_path with Docker tag: $shatag"
            s="${step}" t="${shatag}" yq -i eval '(.$graph[] | select (.id == env(s)) ).hints.DockerRequirement.dockerPull = env(t)' "$cwl_path"
          done

      - name: Upload CWL as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: application-package-${{ matrix.name }}
          path: ${{ matrix.path }}
          overwrite: true

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ matrix.path }}
          asset_name: ${{ matrix.name }}.${{ needs.version.outputs.app-version }}.cwl
          asset_content_type: text/yaml
