name: build
on:
  push:
    branches:
      - master
      - main
    paths:
      - 'inference/**'
      - .github/**
      - 'training/**'
      - codemeta.json

env:
  GHCR_REPO: "ghcr.io/parham-membari-terradue/machine-learning-process-new"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install cwltool
      - run: cwltool --validate training/app-package/tile-sat-training.cwl
      - run: cwltool --validate inference/app-package/tile-sat-inference.cwl

  version:
    needs: validate
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.set-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          APP_VERSION=$(cat codemeta.json | jq -r .version)
          if [ -z "$APP_VERSION" ]; then
            echo "❌ ERROR: Version is missing in codemeta.json"
            exit 1
          fi
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "App version is $APP_VERSION"
      - id: set-version
        run: echo "version=${APP_VERSION}" >> $GITHUB_ENV

  container-build:
    needs: version
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    strategy:
      matrix:
        include:
          - step: training
            path: make-ml-model
          - step: inference
            path: make-inference

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Authenticate to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
      - name: Build & Push Docker Image
        run: |
          IMAGE_ID="${{ env.GHCR_REPO }}/${{ matrix.step }}"
          DOCKERFILE_PATH="${{ matrix.step }}/${{ matrix.path }}/Dockerfile"
          CONTEXT_PATH="${{ matrix.step }}/${{ matrix.path }}"

          echo "Building Docker image from: $DOCKERFILE_PATH"
          docker build "$CONTEXT_PATH" --file "$DOCKERFILE_PATH" --tag "${{ matrix.step }}"

          echo "Tagging image as: $IMAGE_ID:${{ needs.version.outputs.app-version }}"
          docker tag "${{ matrix.step }}" "$IMAGE_ID:${{ needs.version.outputs.app-version }}"
          docker push "$IMAGE_ID:${{ needs.version.outputs.app-version }}"

  create-release:
    needs:
      - container-build
      - version
    runs-on: ubuntu-latest
    permissions:
        contents: write
    outputs:
      upload_url: ${{ steps.set-upload-url.outputs.upload_url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create GitHub Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ needs.version.outputs.app-version }}
          tag_name: ${{ needs.version.outputs.app-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Upload URL
        run: echo "upload_url=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV

  publish-artifacts:
    needs:
      - create-release
      - version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: tile-sat-training
            cwl_path: "training/app-package/tile-sat-training.cwl"
          - name: tile-sat-inference
            cwl_path: "inference/app-package/tile-sat-inference.cwl"
    permissions:
        contents: read
        packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Update CWL files with Docker Image Tags
        run: |
          for step in training inference
          do
            tag="ghcr.io/parham-membari-terradue/machine-learning-process-new/${step}:${{ needs.version.outputs.app-version }}"
            docker pull ${tag}
            
            shatag=$( docker inspect ${tag} | yq -r '.[0]["RepoDigests"][0]' )
            echo "✅ Extracted image SHA: ${shatag}"

            # Select correct CWL file
            if [ "$step" == "training" ]; then
                cwl_path="${{ matrix.cwl_path }}"
            else
                cwl_path="${{ matrix.cwl_path }}"
            fi

            # Ensure the CWL file exists before updating
            if [ ! -f "$cwl_path" ]; then
                echo "❌ ERROR: CWL file not found: $cwl_path"
                exit 1
            fi

            # Update the CWL file with the correct Docker image tag
            yq -i eval '.hints.DockerRequirement.dockerPull = env(shatag)' "$cwl_path"

            echo "✅ Updated $cwl_path with Docker image tag: $shatag"
          done

      - name: Update Metadata in CWL files
        run: |        
          if [ "$step" == "training" ]; then
                cwl_path="${{ matrix.cwl_path }}"
            else
                cwl_path="${{ matrix.cwl_path }}"
            fi

          if [ ! -f "$cwl_path" ]; then
              echo "❌ ERROR: CWL file not found: $cwl_path"
              exit 1
          fi 
          r=$(cat codemeta.json | jq -r ".codeRepository")
          v="${{ needs.version.outputs.app-version }}"
          n=$(cat codemeta.json | jq -r '(.author[0].givenName + " " + .author[0].familyName)')
          e=$(cat codemeta.json | jq -r '.author[0].email')
          a=$(cat codemeta.json | jq -r '.author[0].affiliation["name"]')

          yq -i eval '."s:codeRepository" = {"URL" : env(r)}' "$cwl_path"
          yq -i eval '."s:softwareVersion" = env(v)' "$cwl_path"
          yq -i eval '."s:author" += [{"class": "s:Person", "s.name": env(n), "s.email": env(e), "s.affiliation": env(a)}]' "$cwl_path"

          echo "✅ Successfully updated metadata in $cwl_path"

      - name: Prepare Artifacts for Upload
        run: |
          mkdir -p downloads
          cp "${{ matrix.cwl_path }}" "downloads/${{ matrix.name }}.${{ needs.version.outputs.app-version }}.cwl"

      - name: Upload CWL as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: application-package-${{ matrix.name }}
          path: downloads
          overwrite: true

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: downloads/${{ matrix.name }}.${{ needs.version.outputs.app-version }}.cwl
          asset_name: ${{ matrix.name }}.${{ needs.version.outputs.app-version }}.cwl
          asset_content_type: text/yaml
