name: docs

on:
  push:
    branches:
      - develop
      - main
      - master
    paths:
      - 'docs'
      - 'mkdocs.yml'
      - .github/**

permissions:
  contents: write  # ✅ This is required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - run: pip install mkdocs-material mkdocs-mermaid2-plugin mkdocs-puml-plugin

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
